# Generated by Django 5.0.6 on 2026-05-27 23:20

import apps.books.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True, verbose_name="nombre")),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("country", models.CharField(blank=True, max_length=100, verbose_name="país")),
                ("website", models.URLField(blank=True, verbose_name="sitio web")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "editorial",
                "verbose_name_plural": "editoriales",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("full_name", models.CharField(max_length=200, verbose_name="nombre completo")),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("biography", models.TextField(blank=True, verbose_name="biografía")),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="fecha de nacimiento"),
                ),
                (
                    "death_date",
                    models.DateField(blank=True, null=True, verbose_name="fecha de fallecimiento"),
                ),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=100, verbose_name="nacionalidad"),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.books.models.author_photo_path,
                        verbose_name="foto de perfil",
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="sitio web")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "autor",
                "verbose_name_plural": "autores",
                "ordering": ["full_name"],
                "indexes": [
                    models.Index(fields=["full_name"], name="books_autho_full_na_8fd2c1_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="nombre")),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                ("description", models.TextField(blank=True, verbose_name="descripción")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Lucide icon name",
                        max_length=50,
                        verbose_name="ícono",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6366f1", help_text="Hex color", max_length=7, verbose_name="color"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subcategories",
                        to="books.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "categoría",
                "verbose_name_plural": "categorías",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="título")),
                ("slug", models.SlugField(blank=True, max_length=320, unique=True)),
                (
                    "subtitle",
                    models.CharField(blank=True, max_length=300, verbose_name="subtítulo"),
                ),
                (
                    "isbn",
                    models.CharField(
                        db_index=True, max_length=17, unique=True, verbose_name="ISBN"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="descripción")),
                (
                    "publication_date",
                    models.DateField(blank=True, null=True, verbose_name="fecha de publicación"),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("es", "Español"),
                            ("en", "Inglés"),
                            ("fr", "Francés"),
                            ("de", "Alemán"),
                            ("pt", "Portugués"),
                            ("it", "Italiano"),
                            ("other", "Otro"),
                        ],
                        default="es",
                        max_length=10,
                        verbose_name="idioma",
                    ),
                ),
                (
                    "pages",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="páginas",
                    ),
                ),
                ("edition", models.CharField(blank=True, max_length=50, verbose_name="edición")),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.books.models.book_cover_path,
                        verbose_name="portada",
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=1, verbose_name="stock total")),
                (
                    "available_stock",
                    models.PositiveIntegerField(default=1, verbose_name="stock disponible"),
                ),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="activo"),
                ),
                (
                    "is_featured",
                    models.BooleanField(db_index=True, default=False, verbose_name="destacado"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "authors",
                    models.ManyToManyField(
                        related_name="books", to="books.author", verbose_name="autores"
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="books", to="books.category", verbose_name="categorías"
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="books",
                        to="books.publisher",
                        verbose_name="editorial",
                    ),
                ),
            ],
            options={
                "verbose_name": "libro",
                "verbose_name_plural": "libros",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["isbn"], name="books_book_isbn_54becd_idx"),
                    models.Index(
                        fields=["is_active", "is_featured"], name="books_book_is_acti_629d54_idx"
                    ),
                    models.Index(fields=["available_stock"], name="books_book_availab_cf542a_idx"),
                    models.Index(fields=["language"], name="books_book_languag_ea595e_idx"),
                ],
            },
        ),
    ]
