# Generated by Django 5.0.6 on 2026-05-27 23:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "loan_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="fecha de préstamo"
                    ),
                ),
                ("due_date", models.DateField(verbose_name="fecha de vencimiento")),
                (
                    "return_date",
                    models.DateField(blank=True, null=True, verbose_name="fecha de devolución"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("borrowed", "Prestado"),
                            ("returned", "Devuelto"),
                            ("overdue", "Vencido"),
                            ("cancelled", "Cancelado"),
                        ],
                        db_index=True,
                        default="borrowed",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "fine_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="multa",
                    ),
                ),
                ("fine_paid", models.BooleanField(default=False, verbose_name="multa pagada")),
                (
                    "renewal_count",
                    models.PositiveSmallIntegerField(default=0, verbose_name="renovaciones"),
                ),
                ("notes", models.TextField(blank=True, max_length=500, verbose_name="notas")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loans",
                        to="books.book",
                        verbose_name="libro",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "préstamo",
                "verbose_name_plural": "préstamos",
                "ordering": ["-loan_date"],
                "indexes": [
                    models.Index(
                        fields=["status", "due_date"], name="loans_loan_status_196efd_idx"
                    ),
                    models.Index(fields=["user", "status"], name="loans_loan_user_id_d0fb34_idx"),
                    models.Index(fields=["book", "status"], name="loans_loan_book_id_f87641_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="loan",
            constraint=models.CheckConstraint(
                check=models.Q(("due_date__gte", models.F("loan_date"))),
                name="loan_due_date_after_loan_date",
            ),
        ),
    ]
