# Generated by Django 5.0.6 on 2026-05-27 23:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="calificación",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, verbose_name="título")),
                ("comment", models.TextField(max_length=2000, verbose_name="comentario")),
                (
                    "is_approved",
                    models.BooleanField(db_index=True, default=True, verbose_name="aprobada"),
                ),
                (
                    "helpful_count",
                    models.PositiveIntegerField(default=0, verbose_name="votos útiles"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="books.book",
                        verbose_name="libro",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "reseña",
                "verbose_name_plural": "reseñas",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["book", "is_approved"], name="reviews_rev_book_id_089b4a_idx"
                    ),
                    models.Index(fields=["rating"], name="reviews_rev_rating_2db6dd_idx"),
                ],
                "unique_together": {("user", "book")},
            },
        ),
    ]
