# Generated by Django 5.0.6 on 2026-05-27 23:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("loan_due", "Vencimiento próximo"),
                            ("loan_overdue", "Préstamo vencido"),
                            ("loan_approved", "Préstamo aprobado"),
                            ("loan_returned", "Devolución confirmada"),
                            ("book_available", "Libro disponible"),
                            ("fine_issued", "Multa generada"),
                            ("system", "Sistema"),
                        ],
                        db_index=True,
                        default="system",
                        max_length=30,
                        verbose_name="tipo",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="título")),
                ("message", models.TextField(verbose_name="mensaje")),
                (
                    "is_read",
                    models.BooleanField(db_index=True, default=False, verbose_name="leída"),
                ),
                ("loan_id", models.UUIDField(blank=True, null=True)),
                ("book_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "notificación",
                "verbose_name_plural": "notificaciones",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "is_read"], name="notificatio_user_id_427e4b_idx"),
                    models.Index(fields=["type"], name="notificatio_type_ea918f_idx"),
                ],
            },
        ),
    ]
